name = "Tropical"
uuid = "6b483f74-7a2e-47cf-8bae-b69f5323f383"
authors = ["Argel Ram√≠rez Reyes <argel.ramirez@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
